name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:

  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Select release version
        id: version
        run: printf 'version=1.%(%Y%m%d.%H%M)T' >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Publish to NPM
        run: |
          echo 'Setting version ${{ steps.version.outputs.version }} in package descriptor'
          sed -i -e 's|0.0.0|${{ steps.version.outputs.version }}|g' package.json
          npm install
          npm publish --access public --//registry.npmjs.org:_authToken=${{ secrets.NPM_TOKEN }}
